<a href="https://colab.research.google.com/github/sumpumm/ML-from-scratch/blob/main/01%20Introduction_to_ML/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Introduction to numpy

what will be be covering ?
- creating arrays
- multidimensional array
- randomly generated arrays
- element wise operations
  - comparison operations
  - Logical operations
- summarizaing operations


---




###✅single dimensional arrays

In [1]:
import numpy as np


creating arrays

In [4]:
a=np.zeros(5)
print(type(a))

<class 'numpy.ndarray'>


In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [9]:
np.full((2, 3) ,5)

array([[5, 5, 5],
       [5, 5, 5]])

In [13]:
my_arr=np.array([1, 2, 3, 4, 5])
my_arr[2]= 5
print(my_arr)

[1 2 5 4 5]


In [14]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

create arrays with evenly spaced numbers within a specififed range

In [20]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

### ✅Multidimensional arrays

In [23]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [26]:
np.full((2,5),7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [48]:
mult_arr=np.array([[1,2,3,4,5],
                  [12,54,6,7,1],
                  [1,7,8,4,2]])
mult_arr[2]=np.ones(5)
mult_arr[:,4]=[2,2,2]
mult_arr

array([[ 1,  2,  3,  4,  2],
       [12, 54,  6,  7,  2],
       [ 1,  1,  1,  1,  2]])

### ✅Randomly generated arrays

- NumPy can create arrays filled with random numbers.
- to ensure the reproductivity, you can set a seed using np.random.seed() function
- Everytime you run the code with np.random.seed(2), it will generate the exact same random numbers. If you remove or change the seed value, the sequence of random numbers will change!

In [63]:
np.random.rand(3) #this function gives random number only in the interval 0-1


array([0.69466891, 0.60851481, 0.401272  ])

In [76]:
np.random.seed(1)
np.random.rand(3)

array([4.17022005e-01, 7.20324493e-01, 1.14374817e-04])

In [82]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [90]:
np.random.randn(5,2) #normally distributed random numbers with mean 0 and SD 1

array([[-0.18946926, -0.07721867],
       [ 0.82470301,  1.24821292],
       [-0.40389227, -1.38451867],
       [ 1.36723542,  1.21788563],
       [-0.46200535,  0.35088849]])

In [92]:
np.random.seed(42)
np.random.randint(low=0,high=100,size=(5,2))

array([[51, 92],
       [14, 71],
       [60, 20],
       [82, 86],
       [74, 74]])

### ✅Element wise operations

In [93]:
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [95]:
b=(10+(a*2))
b

array([10, 12, 14, 16, 18])

###✅Comparison operations


In [96]:
#you can perform element wise comparisons and create boolean arrays
a >=2

array([False, False,  True,  True,  True])

In [98]:
a > b

array([False, False, False, False, False])

In [100]:
#Summarizing
# NumPy provides functions for summarizing array of data
a

array([0, 1, 2, 3, 4])

In [102]:
a.std() # standard deviation

1.4142135623730951

In [105]:
a.mean()

2.0

In [107]:
a.min()

0

In [108]:
a.max()

4

In [109]:
a.sum()

10